export default function PrivacyPolicyEn() {
  return (
    <section id="main" className="wrapper">
      <div className="inner">
        <h1 className="major">Privacy Policy</h1>

        <p>Created / Effective date: 30.04.2026</p>

        <h2>Contents</h2>

        <ul>
          <li>What data we collect</li>
          <li>How and why we use collected data</li>
          <li>Google Analytics</li>
          <li>Content and intellectual property</li>
          <li>Users under 18</li>
          <li>Data security</li>
          <li>Changes to this Privacy Policy</li>
        </ul>

        <p>
          Pipe Digital SRL respects the privacy of users of the Mesaje din
          Suflet application. This Privacy Policy describes how the Mesaje din
          Suflet mobile application (hereinafter "the App") handles user
          information.
        </p>
        <p>
          By using the App, you confirm that you have read and accepted the
          provisions of this Privacy Policy.
        </p>

        <h2>What data we collect</h2>

        <p>
          The Mesaje din Suflet app{" "}
          <strong className="light">does not collect any personal data</strong>{" "}
          from its users. No account creation, login, or provision of any
          personal information is required to use the App.
        </p>
        <p>
          Greeting card content (messages, visual styles) is loaded from an
          external server when the App is opened. These network requests do not
          transmit any personal data.
        </p>
        <p>
          Data collected is limited to anonymous usage statistics via Google
          Analytics and data generated by the advertising network, both
          described below.
        </p>

        <h2>How and why we use collected data</h2>

        <p>
          The anonymous usage statistics collected through Google Analytics are
          used exclusively for:
        </p>
        <ul>
          <li>
            <strong className="light">App performance analysis.</strong>{" "}
            Understanding how users interact with the App in order to improve
            the overall experience.
          </li>
          <li>
            <strong className="light">Identifying technical issues.</strong>{" "}
            Detecting technical problems and resolving them quickly.
          </li>
          <li>
            <strong className="light">Developing new features.</strong> Making
            informed decisions about future improvements to the App based on
            anonymous usage patterns.
          </li>
        </ul>
        <p>
          This data is not used for marketing purposes and is not sold or
          transferred to third parties for commercial gain.
        </p>

        <h2>Google Analytics</h2>

        <p>
          The App uses Google Analytics to collect anonymous usage statistics.
          Google Analytics collects information such as number of sessions,
          session duration, device type, and operating system — all in a fully
          anonymised form that cannot identify an individual user.
        </p>
        <p>
          Data collected by Google Analytics is subject to{" "}
          <a
            href="https://policies.google.com/privacy"
            target="_blank"
            rel="noopener noreferrer"
          >
            Google's Privacy Policy
          </a>
          . Pipe Digital SRL does not have access to any data that could
          personally identify users through Google Analytics.
        </p>
        <p>
          We do not use tracking cookies or any other personal identification
          mechanisms.
        </p>

        <h2>Advertising</h2>

        <p>
          The App displays banner advertisements provided by third-party
          advertising networks, most likely Google Ads (Google AdMob). These
          networks may automatically collect certain data from your device in
          order to show relevant ads, including:
        </p>
        <ul>
          <li>
            Device advertising identifiers (e.g. IDFA on iOS, GAID on Android)
          </li>
          <li>
            Approximate IP address and geographic location at country/region
            level
          </li>
          <li>Device type, operating system, and language settings</li>
          <li>Interactions with displayed advertisements</li>
        </ul>
        <p>
          Pipe Digital SRL does not have direct access to the data collected by
          advertising networks and does not control it. The collection and use
          of this data is governed by the privacy policy of the respective
          provider. For Google Ads / AdMob, please refer to the{" "}
          <a
            href="https://policies.google.com/privacy"
            target="_blank"
            rel="noopener noreferrer"
          >
            Google Privacy Policy
          </a>
          .
        </p>
        <p>
          Users can limit ad tracking through their device settings (iOS:
          Settings → Privacy → Advertising; Android: Settings → Google → Ads).
        </p>

        <h2>Content and intellectual property</h2>

        <p>
          All content available in the App — including greeting messages, texts,
          visual styles, and graphic design — is created with the assistance of
          artificial intelligence and is the exclusive property of{" "}
          <strong className="light">Pipe Digital SRL</strong>. This content is
          protected by applicable copyright law.
        </p>
        <p>
          Users may customise the text and style of greeting cards within the
          App and export the result as an image (JPG file) for personal use and
          sharing. Pipe Digital SRL does not claim any rights over the personal
          modifications users add to their own exports.
        </p>
        <p>
          Unauthorised commercial use of the App's original content is
          prohibited without the written consent of Pipe Digital SRL.
        </p>

        <h2>Users under 18</h2>

        <p>
          The Mesaje din Suflet app is available to any user, regardless of age.
          Since the App does not collect personal data, there are no age
          restrictions on use and no parental consent is required from a data
          protection standpoint.
        </p>

        <h2>Data security</h2>

        <p>
          The App does not collect or store personal data from users. Greeting
          card content is delivered over secure connections (HTTPS) from our
          servers. Anonymous statistics collected through Google Analytics and
          data generated by advertising are managed in accordance with the
          security standards of their respective providers.
        </p>
        <p>
          Images exported by users (JPG files generated in the App) are saved
          locally on the user's device and are the user's responsibility with
          regard to subsequent sharing.
        </p>

        <h2>Changes to this Privacy Policy</h2>

        <p>
          We reserve the right to modify this Privacy Policy. Any significant
          change will be communicated by updating the effective date shown at
          the beginning of this document. We recommend checking this page
          periodically. Continued use of the App after changes are published
          constitutes acceptance of the updated Privacy Policy.
        </p>

        <p>
          Questions regarding this Privacy Policy should be directed to{" "}
          <a href="mailto:alexapostol.m@gmail.com">alexapostol.m@gmail.com</a>
        </p>
      </div>
    </section>
  );
}
